[versions]

plugin-android = "8.12.3"
plugin-maven-publish = "0.34.0"

compose = "1.9.1"
composeCompiler = "1.5.15"

kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlin = "2.2.0"

korio = { module = "com.soywiz.korlibs.korio:korio", version.ref = "korio" }

kermit = "2.0.8"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

touchlab-kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

[plugins]
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "plugin-maven-publish" }
